config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'
  resources :votes, only: :create
  resources :bill_posts, only: :index
end

app/views/pages/_bills.html.erb
<% bill_posts.each do |bill_post| %>
	<article class="bg-white p-4">
		<div class="flex">
			<%= turbo_frame_tag "#{dom_id(bill_post)}-voting" do %>
				<%= render "pages/vote", 
										bill_post: bill_post,
										vote_result: cookies["bill_post_#{bill_post.id}_vote"] %>
			<% end %>
		  <div class="flex-1">
		    <h4 class="text-xl font-bold"><%= bill_post.title %></h4>
		    <br>
		    <div class="mt-1">
		    	<ul class="text-lg">
		    		<%= bill_post.description %>
		    	</ul>
		    </div>
		    <br>

		   	<% bill_post.tags.sort.each do |tag| %>
		    	<span class="inline-flex items-center rounded-md shadow bg-pink-600 text-white px-2 py-1 text-lg text-gray-600 mx-1"><%= format_tag_name(tag.name) %></span>
		    <% end %>

		    <br>
		    <br>
		    <br>
		    <br>
		    <% votes_percentage = bill_post.calculate_vote_percentage %>
		    <% upvote_percentage = votes_percentage[:upvote_percentage] %>
		    <% downvote_percentage = votes_percentage[:downvote_percentage] %>
		    <%= render "pages/voting_progress",
		    						total_votes: bill_post.total_votes,
		    						upvote_percentage: upvote_percentage,
		    						downvote_percentage: downvote_percentage %>
		    <br>
		   	<hr>
		   	<br>
		   	<div class="grid grid-cols-12 gap-4">
		   		<button class="col-span-4 h-16 border-2 rounded flex justify-center items-center hover:border-pink-600">
						<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
						  <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
						</svg>
		   		</button>
					<button class="col-span-4 h-16 border-2 rounded flex justify-center items-center hover:border-pink-600">
						<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
						  <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m2.25 0H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z" />
						</svg>
		   		</button>				   		
					<button class="col-span-4 h-16 border-2 rounded flex justify-center items-center hover:border-pink-600">
						<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
						  <path stroke-linecap="round" stroke-linejoin="round" d="M7.217 10.907a2.25 2.25 0 1 0 0 2.186m0-2.186c.18.324.283.696.283 1.093s-.103.77-.283 1.093m0-2.186 9.566-5.314m-9.566 7.5 9.566 5.314m0 0a2.25 2.25 0 1 0 3.935 2.186 2.25 2.25 0 0 0-3.935-2.186Zm0-12.814a2.25 2.25 0 1 0 3.933-2.185 2.25 2.25 0 0 0-3.933 2.185Z" />
						</svg>
		   		</button>				   		
		   	</div>
		  </div>
		</div>				
	</article>
	<br>
<% end %>
<p class="text-center"><%= bill_posts.size %></p>

app/views/pages/_filter.html.erb
<p class="text-xl font-bold">Filter by tags</p>
<br>
<%= form_with(url: bill_posts_path, method: :get, class: "space-y-5", data: { controller: "filter", turbo_stream: true }) do %>
	<% Tag::TAGS.sort.each do |tag| %>
    <div class="relative flex items-start">
      <div class="flex h-6 items-center">
      	<%= check_box_tag "filter[]", 
      										tag,
      										params[:tag]&.include?(tag),
      										id: "#{tag}",
      										class: "hover:cursor-pointer h-5 w-5 rounded border-2 border-gray-300 text-pink-600 focus:ring-pink-600",
      										data: {
      											action: "change->filter#submit"
      										} %>

      </div>
      <div class="ml-3 text-lg leading-6">
      	<%= label_tag tag, 
      								tag,
      								class: "hover:cursor-pointer font-medium text-gray-900" %>
      </div>
    </div>
	<% end %>
<% end %>

app/views/pages/_next_page.html.erb
<% if @pagy.page == @pagy.last %>
	<p class="text-center">fin</p>
<% else %>
	<%= turbo_frame_tag "bill-posts-page-#{@pagy.next}",
											loading: :lazy,
											src: pagy_url_for(@pagy, @pagy.next),
											target: "_top" do %>
	<p class="text-center">loading...</p>
	<% end %>
<% end %>

app/views/pages/_vote.html.erb
<div class="mr-4 self-start">
	<div class="flex flex-col items-center bg-gray-100 min-w-20">
		<% up_vote_method = vote_result == "up_vote" ? "delete" : "post" %>
		<% up_vote_path = up_vote_method == "delete" ? destroy_vote_votes_path(bill_post_id: bill_post.id, vote_type: "up_vote") : votes_path(bill_post_id: bill_post.id, vote_type: "up_vote") %>

		<%= button_to up_vote_path,
									method: up_vote_method,
								  class: "h-10 flex justify-center items-center w-12 rounded-full m-2 hover:bg-gray-300 outline-none border-none" do %>
			<svg  xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 <%= vote_result == "up_vote" ? "voted" : "" %>">
			  <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 10.5 12 3m0 0 7.5 7.5M12 3v18" />
			</svg>
		<% end %>

		<p class="bg-pink-600 text-white text-center px-4 rounded">
			<strong>
				<% if vote_result.present? %>
					Voted
				<% end %>
			</strong>
		</p>
		<% down_vote_method = vote_result == "down_vote" ? "delete" : "post" %>
		<% down_vote_path = down_vote_method == "delete" ? destroy_vote_votes_path(bill_post_id: bill_post.id, vote_type: "down_vote") : votes_path(bill_post_id: bill_post.id, vote_type: "down_vote") %>

		<%= button_to down_vote_path,
									method: down_vote_method,
								  class: "h-10 flex justify-center items-center w-12 rounded-full m-2 hover:bg-gray-300 outline-none border-none" do %>
			<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 <%= vote_result == "down_vote" ? "voted" : "" %>">
			  <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 13.5 12 21m0 0-7.5-7.5M12 21V3" />
			</svg>
		<% end %>
	</div>
</div>

app/views/pages/_voting_progress.html.erb
<div class="progress-container">
  <div class="upvote-section bg-green-500" style="width: <%= upvote_percentage %>%;">
    <div class="tooltip">Up: <%= upvote_percentage %>%</div>
  </div>
  <div class="downvote-section bg-gray-300" style="width: <%= downvote_percentage %>%;">
    <div class="tooltip">Down: <%= downvote_percentage %>%</div>
  </div>
</div>
<div class="text-center">Total Votes: <%= number_to_human(total_votes, units: { thousand: 'k', million: 'M' }, precision: 1) %></div>

app/views/pages/home.html.erb
<div class="mt-16 mx-auto max-w-7xl px-4 sm:mt-24">
	<div class="grid grid-cols-12 gap-4">
		<aside id="sidebar" class="col-span-3 bg-white sticky top-0 p-4 pb-6 h-max">
			<%= render "filter"  %>
		</aside>
		<main id="content" class="col-span-9">
			<%= turbo_frame_tag "bills", target: '_top' do %>
				<%= render "bills", bill_posts: @bill_posts %>
			<% end %>
		</main>
	</div>
</div>

app/views/pages/scrollable_list.html.erb
<%= turbo_frame_tag "bill-posts-page-#{@pagy.page}" do %>
	<%= render "bills", bill_posts: @bill_posts %>
	<%= render partial: "next_page" %>
<% end %>s